### ISSUE TITLE
Testing: Deleting a 100 section item is not removing all the sections in the item in Mallorn

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1989]
### Descriptive summary
Server: mallorn.dlib.indiana.edu
Testing: Performance
Browser: Chrome(58.0.3029.110 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Deleting a 100 section item is not removing all the sections in the item.

### Expected behavior
The item gets deleted from the Avalon system completely.

### Actual behavior
In one try there are 30 sections leftover out of the 100 sections.

### Steps to reproduce the behavior
1. Login to mallorn system.
2. Add a 100 section item.
3. After the item is added, browse for the item and click the checkbox next to it to select the item.
4. Go to the Managed Selected Objects page and click on delete button.
5. Wait for some time (around 2hrs) and verify if the item is removed completely.

### Related work
Speed up MediaObject destroy #2047

**Comment by phuongdh** [comment]
- [ ] Move delete job to background.
- [ ] Reduce number of callbacks that update relationships.

**Comment by Karthikeya212** [comment]
This issue is reproduced on Mallorn today. The system deleted 79sections from the item and left 21sections as it is. This is the item in Mallorn: https://mallorn.dlib.indiana.edu/media_objects/3f462543d

**Comment by phuongdh** [comment]
Because the deletion process would take longer than 2h, I or someone else might have messed with the server before it got to completion. I think we should try to reproduce this bug in a more controlled way.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners Given that @Karthikeya212 said this was fixed the last time he tested and that we have #2047, can we close this issue?

**Comment by Karthikeya212** [comment]
@cjcolvar The issue that is fixed was the failure of 100section delete from preview page #1965 , as in that case the delete operation itself is not triggering. Phuong gave a fix for that by triggering a background process for the delete operation and not allowing it to terminate in the preview page. Sorry for any mis-communication.

The issue in the current bug(not deleting the item completely) is yet to be tested, the testing is blocked last week because of the ActiveEncode issue as I couldn't create 100section item. Given the active-encode issue is fixed now I will test this bug next week in an isolated environment.

**Comment by cjcolvar** [comment]
Ok, sounds good.

**Comment by joncameron** [comment]
This issue is now just for testing to verify that this is still occurring, as per the comment chain.

**Comment by Karthikeya212** [comment]
Tested it, and the delete operation of a 100 section item is successful.
